name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check_description:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: print_description
      run: |
        echo ${{ github.event.number }}

